/**
 * Comprehensive static database of global entrance exams.
 * Structured by country, stream category, and degree eligibility.
 */

export const EXAM_DATABASE = [
  // ================= INDIA =================
  {
    id: "jee_main",
    name: "JEE Main",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.E", "B.Arch", "B.Plan"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://jeemain.nta.ac.in",
    category: "Engineering",
    examLevelScope: "National",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "jee_adv",
    name: "JEE Advanced",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.S.", "Dual Degree B.Tech-M.Tech"],
    conductingBody: "Joint Admission Board (JAB) / IITs",
    website: "https://jeeadv.ac.in",
    category: "Engineering",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 1000000,
    hint: "Enter your All India Rank (AIR)"
  },
  {
    id: "bitsat",
    name: "BITSAT",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.E.", "B.Pharm", "M.Sc. (Integrated)"],
    conductingBody: "BITS Pilani",
    website: "https://www.bitsadmission.com",
    category: "Engineering",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 390,
    hint: "Range: 0 - 390 score"
  },
  {
    id: "viteee",
    name: "VITEEE",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech"],
    conductingBody: "Vellore Institute of Technology (VIT)",
    website: "https://viteee.vit.ac.in",
    category: "Engineering",
    examLevelScope: "University",
    score_type: "rank",
    min_val: 1,
    max_val: 200000,
    hint: "Enter your VITEEE rank"
  },
  {
    id: "srmjeee",
    name: "SRMJEEE",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech"],
    conductingBody: "SRM Institute of Science and Technology",
    website: "https://www.srmist.edu.in",
    category: "Engineering",
    examLevelScope: "University",
    score_type: "rank",
    min_val: 1,
    max_val: 100000,
    hint: "Enter your SRMJEEE rank"
  },
  {
    id: "comedk",
    name: "COMEDK UGET",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.Arch"],
    conductingBody: "Consortium of Medical, Engineering and Dental Colleges of Karnataka",
    website: "https://www.comedk.org",
    category: "Engineering",
    examLevelScope: "State",
    score_type: "rank",
    min_val: 1,
    max_val: 150000,
    hint: "Enter your COMEDK rank"
  },
  {
    id: "wbjee",
    name: "WBJEE",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.Pharm"],
    conductingBody: "West Bengal Joint Entrance Examinations Board",
    website: "https://wbjeeb.nic.in",
    category: "Engineering",
    examLevelScope: "State",
    score_type: "rank",
    min_val: 1,
    max_val: 150000,
    hint: "Enter your General Merit Rank (GMR)"
  },
  {
    id: "kcet",
    name: "KCET",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.E.", "B.Pharm", "B.Sc. Agriculture", "B.V.Sc."],
    conductingBody: "Karnataka Examinations Authority (KEA)",
    website: "https://cetonline.karnataka.gov.in/kea",
    category: "Engineering",
    examLevelScope: "State",
    score_type: "rank",
    min_val: 1,
    max_val: 250000,
    hint: "Enter your KCET rank"
  },
  {
    id: "mhtcet",
    name: "MHT CET",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.Pharm", "Pharm.D"],
    conductingBody: "State Common Entrance Test Cell, Maharashtra",
    website: "https://cetcell.mahacet.org",
    category: "Engineering",
    examLevelScope: "State",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "ap_eamcet",
    name: "AP EAPCET",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.Pharm", "B.Sc. Agriculture", "Pharm.D"],
    conductingBody: "JNTU Anantapur on behalf of APSCHE",
    website: "https://sche.ap.gov.in",
    category: "Engineering",
    examLevelScope: "State",
    score_type: "rank",
    min_val: 1,
    max_val: 300000,
    hint: "Enter your AP EAPCET rank"
  },
  {
    id: "ts_eamcet",
    name: "TG EAPCET",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Tech", "B.Pharm", "B.Sc. Agriculture", "Pharm.D"],
    conductingBody: "JNTU Hyderabad on behalf of TSCHE",
    website: "https://eapcet.tsche.ac.in",
    category: "Engineering",
    examLevelScope: "State",
    score_type: "rank",
    min_val: 1,
    max_val: 200000,
    hint: "Enter your TG EAPCET rank"
  },
  {
    id: "gate",
    name: "GATE",
    country: "India",
    level: "PG",
    eligibleCourses: ["M.Tech", "M.E.", "Ph.D.", "PSU Recruitment"],
    conductingBody: "IITs / IISc",
    website: "https://gate.iitkgp.ac.in",
    category: "Engineering",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 1000,
    hint: "Enter your GATE score (out of 1000)"
  },
  {
    id: "neet_ug",
    name: "NEET UG",
    country: "India",
    level: "UG",
    eligibleCourses: ["MBBS", "BDS", "BAMS", "BHMS", "BUMS", "BSMS"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://neet.nta.nic.in",
    category: "Medical",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 720,
    hint: "Range: 0 - 720 marks"
  },
  {
    id: "neet_pg",
    name: "NEET PG",
    country: "India",
    level: "PG",
    eligibleCourses: ["MD", "MS", "PG Diploma"],
    conductingBody: "National Board of Examinations (NBE)",
    website: "https://nbe.edu.in",
    category: "Medical",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 150000,
    hint: "Enter your NEET PG rank"
  },
  {
    id: "ini_cet",
    name: "INI CET",
    country: "India",
    level: "PG",
    eligibleCourses: ["MD", "MS", "M.Ch", "DM", "MDS"],
    conductingBody: "All India Institute of Medical Sciences (AIIMS)",
    website: "https://www.aiimsexams.ac.in",
    category: "Medical",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 100000,
    hint: "Enter your INI CET percentile rank"
  },
  {
    id: "cuet_ug",
    name: "CUET UG",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Sc.", "B.A.", "B.Com", "BBA", "BCA", "Integrated Law"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://cuet.samarth.ac.in",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 1200,
    hint: "Enter cumulative normalized score"
  },
  {
    id: "cuet_pg",
    name: "CUET PG",
    country: "India",
    level: "PG",
    eligibleCourses: ["M.Sc.", "M.A.", "M.Com", "MBA", "MCA"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://pgcuet.samarth.ac.in",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 400,
    hint: "Range: 0 - 400 marks"
  },
  {
    id: "iat",
    name: "IISER Aptitude Test (IAT)",
    country: "India",
    level: "UG",
    eligibleCourses: ["BS-MS Dual Degree", "BS Degree"],
    conductingBody: "IISER Admission Joint Admissions Committee",
    website: "https://iiseradmission.in",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 240,
    hint: "Range: 0 - 240 marks"
  },
  {
    id: "nest",
    name: "NEST",
    country: "India",
    level: "UG",
    eligibleCourses: ["Integrated M.Sc."],
    conductingBody: "NISER Bhubaneswar & UM-DAE CEBS Mumbai",
    website: "https://www.nestexam.in",
    category: "Science",
    examLevelScope: "National",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "icar_aieea",
    name: "ICAR AIEEA (UG)",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Sc. Agriculture", "B.Sc. Forestry", "B.Sc. Horticulture", "B.Tech Agriculture"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://icar.nta.ac.in",
    category: "Agriculture",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 100000,
    hint: "Enter your ICAR rank"
  },
  {
    id: "cat",
    name: "CAT",
    country: "India",
    level: "PG",
    eligibleCourses: ["MBA", "PGDM", "FPM"],
    conductingBody: "Indian Institutes of Management (IIMs)",
    website: "https://iimcat.ac.in",
    category: "Management",
    examLevelScope: "National",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "xat",
    name: "XAT",
    country: "India",
    level: "PG",
    eligibleCourses: ["MBA", "PGDM"],
    conductingBody: "XLRI Jamshedpur",
    website: "https://www.xatonline.in",
    category: "Management",
    examLevelScope: "National",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "snap",
    name: "SNAP",
    country: "India",
    level: "PG",
    eligibleCourses: ["MBA", "M.Sc. (CA)", "M.Sc. (SS)"],
    conductingBody: "Symbiosis International University",
    website: "https://www.snaptest.org",
    category: "Management",
    examLevelScope: "University",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "nmat",
    name: "NMAT",
    country: "India",
    level: "PG",
    eligibleCourses: ["MBA", "PGDM"],
    conductingBody: "Graduate Management Admission Council (GMAC)",
    website: "https://www.register.nmat.org",
    category: "Management",
    examLevelScope: "National",
    score_type: "score",
    min_val: 120,
    max_val: 360,
    hint: "Range: 120 - 360"
  },
  {
    id: "cmat",
    name: "CMAT",
    country: "India",
    level: "PG",
    eligibleCourses: ["MBA", "PGDM"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://cmat.nta.nic.in",
    category: "Management",
    examLevelScope: "National",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "mat",
    name: "MAT",
    country: "India",
    level: "PG",
    eligibleCourses: ["MBA", "PGDM"],
    conductingBody: "All India Management Association (AIMA)",
    website: "https://www.aima.in",
    category: "Management",
    examLevelScope: "National",
    score_type: "percentile",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 percentile"
  },
  {
    id: "ipmat",
    name: "IPMAT",
    country: "India",
    level: "UG",
    eligibleCourses: ["Integrated Programme in Management (IPM)"],
    conductingBody: "IIM Indore / IIM Rohtak",
    website: "https://www.iimidr.ac.in",
    category: "Management",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 400,
    hint: "Range: 0 - 400 score"
  },
  {
    id: "clat",
    name: "CLAT (UG)",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.A. LLB", "B.B.A. LLB", "B.Com. LLB", "B.Sc. LLB"],
    conductingBody: "Consortium of National Law Universities",
    website: "https://consortiumofnlus.ac.in",
    category: "Law",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 50000,
    hint: "Enter your Common Law Admission Test rank"
  },
  {
    id: "clat_pg",
    name: "CLAT PG",
    country: "India",
    level: "PG",
    eligibleCourses: ["LL.M."],
    conductingBody: "Consortium of National Law Universities",
    website: "https://consortiumofnlus.ac.in",
    category: "Law",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 20000,
    hint: "Enter your CLAT PG rank"
  },
  {
    id: "ailet",
    name: "AILET",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.A. LLB", "LLM", "Ph.D."],
    conductingBody: "National Law University, Delhi",
    website: "https://nationallawuniversitydelhi.in",
    category: "Law",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 10000,
    hint: "Enter AILET rank"
  },
  {
    id: "uceed",
    name: "UCEED",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Des"],
    conductingBody: "IIT Bombay",
    website: "https://www.uceed.iitb.ac.in",
    category: "Design",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 20000,
    hint: "Enter your UCEED rank"
  },
  {
    id: "nid_dat",
    name: "NID DAT",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Des", "M.Des"],
    conductingBody: "National Institute of Design",
    website: "https://admissions.nid.edu",
    category: "Design",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 15000,
    hint: "Enter NID DAT rank"
  },
  {
    id: "nift",
    name: "NIFT Entrance Exam",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Des", "B.F.Tech", "M.Des", "M.F.M.", "M.F.Tech"],
    conductingBody: "National Institute of Fashion Technology",
    website: "https://nift.ac.in",
    category: "Design",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 25000,
    hint: "Enter NIFT merit rank"
  },
  {
    id: "ceed",
    name: "CEED",
    country: "India",
    level: "PG",
    eligibleCourses: ["M.Des", "Ph.D."],
    conductingBody: "IIT Bombay",
    website: "https://www.ceed.iitb.ac.in",
    category: "Design",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 100,
    hint: "Enter CEED score"
  },
  {
    id: "nata",
    name: "NATA",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Arch"],
    conductingBody: "Council of Architecture (CoA)",
    website: "https://www.nata.in",
    category: "Architecture",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 200,
    hint: "Range: 0 - 200 marks"
  },
  {
    id: "nda",
    name: "NDA",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Sc.", "B.A.", "B.Tech (Military/Navy/AirForce Training)"],
    conductingBody: "Union Public Service Commission (UPSC)",
    website: "https://www.upsc.gov.in",
    category: "Defence",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 900,
    hint: "Enter written exam marks (out of 900)"
  },
  {
    id: "nchmct_jee",
    name: "NCHM JEE",
    country: "India",
    level: "UG",
    eligibleCourses: ["B.Sc. Hospitality and Hotel Administration"],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://nchmjee.nta.nic.in",
    category: "Hotel Management",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 50000,
    hint: "Enter NCHM JEE rank"
  },
  {
    id: "gpat",
    name: "GPAT",
    country: "India",
    level: "PG",
    eligibleCourses: ["M.Pharm", "Ph.D."],
    conductingBody: "National Testing Agency (NTA)",
    website: "https://gpat.nta.nic.in",
    category: "Pharmacy",
    examLevelScope: "National",
    score_type: "rank",
    min_val: 1,
    max_val: 60000,
    hint: "Enter GPAT All India Rank"
  },

  // ================= UNITED STATES =================
  {
    id: "sat",
    name: "SAT",
    country: "United States",
    level: "UG",
    eligibleCourses: ["Bachelor of Science (B.S.)", "Bachelor of Arts (B.A.)"],
    conductingBody: "College Board",
    website: "https://satsuite.collegeboard.org",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 400,
    max_val: 1600,
    hint: "Range: 400 - 1600"
  },
  {
    id: "act",
    name: "ACT",
    country: "United States",
    level: "UG",
    eligibleCourses: ["Bachelor of Science (B.S.)", "Bachelor of Arts (B.A.)"],
    conductingBody: "ACT Inc.",
    website: "https://www.act.org",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 1,
    max_val: 36,
    hint: "Range: 1 - 36"
  },
  {
    id: "gre",
    name: "GRE General",
    country: "United States",
    level: "PG",
    eligibleCourses: ["Master of Science (M.S.)", "Ph.D.", "MBA"],
    conductingBody: "Educational Testing Service (ETS)",
    website: "https://www.ets.org/gre",
    category: "Engineering",
    examLevelScope: "National",
    score_type: "score",
    min_val: 260,
    max_val: 340,
    hint: "Range: 260 - 340"
  },
  {
    id: "gmat",
    name: "GMAT Focus Edition",
    country: "United States",
    level: "PG",
    eligibleCourses: ["MBA", "Master in Management (MiM)", "Master of Science"],
    conductingBody: "Graduate Management Admission Council (GMAC)",
    website: "https://www.mba.com",
    category: "Management",
    examLevelScope: "National",
    score_type: "score",
    min_val: 205,
    max_val: 805,
    hint: "Range: 205 - 805"
  },
  {
    id: "lsat",
    name: "LSAT",
    country: "United States",
    level: "PG",
    eligibleCourses: ["Juris Doctor (J.D.)", "LL.M."],
    conductingBody: "Law School Admission Council (LSAC)",
    website: "https://www.lsac.org",
    category: "Law",
    examLevelScope: "National",
    score_type: "score",
    min_val: 120,
    max_val: 180,
    hint: "Range: 120 - 180"
  },
  {
    id: "mcat",
    name: "MCAT",
    country: "United States",
    level: "PG",
    eligibleCourses: ["Doctor of Medicine (M.D.)", "Doctor of Osteopathic Medicine (D.O.)"],
    conductingBody: "Association of American Medical Colleges (AAMC)",
    website: "https://students-residents.aamc.org",
    category: "Medical",
    examLevelScope: "National",
    score_type: "score",
    min_val: 472,
    max_val: 528,
    hint: "Range: 472 - 528"
  },
  {
    id: "dat",
    name: "DAT",
    country: "United States",
    level: "PG",
    eligibleCourses: ["Doctor of Dental Surgery (D.D.S.)", "Doctor of Medicine in Dentistry (D.M.D.)"],
    conductingBody: "American Dental Association (ADA)",
    website: "https://www.ada.org/education/testing/exams/dental-admission-test-dat",
    category: "Medical",
    examLevelScope: "National",
    score_type: "score",
    min_val: 1,
    max_val: 30,
    hint: "Range: 1 - 30 Academic Average"
  },

  // ================= UNITED KINGDOM =================
  {
    id: "ucat",
    name: "UCAT (UK)",
    country: "United Kingdom",
    level: "UG",
    eligibleCourses: ["MBChB (Medicine)", "BDS (Dentistry)"],
    conductingBody: "UCAT Consortium",
    website: "https://www.ucat.ac.uk",
    category: "Medical",
    examLevelScope: "National",
    score_type: "score",
    min_val: 1200,
    max_val: 3600,
    hint: "Range: 1200 - 3600 cognitive sum"
  },
  {
    id: "lnat",
    name: "LNAT",
    country: "United Kingdom",
    level: "UG",
    eligibleCourses: ["Bachelor of Laws (LL.B.)"],
    conductingBody: "LNAT Consortium",
    website: "https://lnat.ac.uk",
    category: "Law",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 42,
    hint: "Range: 0 - 42"
  },
  {
    id: "mat_oxford",
    name: "MAT (Oxford)",
    country: "United Kingdom",
    level: "UG",
    eligibleCourses: ["BA Mathematics", "MMath", "BA Computer Science"],
    conductingBody: "University of Oxford",
    website: "https://www.ox.ac.uk/admissions/undergraduate/applying-to-oxford/guide/admissions-tests/mat",
    category: "Science",
    examLevelScope: "University",
    score_type: "score",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 marks"
  },
  {
    id: "pat",
    name: "PAT",
    country: "United Kingdom",
    level: "UG",
    eligibleCourses: ["MEng Engineering Science", "BA Physics"],
    conductingBody: "University of Oxford",
    website: "https://www.ox.ac.uk/admissions/undergraduate/applying-to-oxford/guide/admissions-tests/pat",
    category: "Engineering",
    examLevelScope: "University",
    score_type: "score",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 marks"
  },
  {
    id: "step",
    name: "STEP",
    country: "United Kingdom",
    level: "UG",
    eligibleCourses: ["BA Mathematics (Cambridge / Warwick)"],
    conductingBody: "Cambridge Assessment Admissions Testing",
    website: "https://www.admissionstesting.org/for-test-takers/step",
    category: "Science",
    examLevelScope: "University",
    score_type: "score",
    min_val: 1,
    max_val: 3,
    hint: "Enter Grade: 1 (Outstanding), 2 (Very Good), 3 (Good)"
  },

  // ================= CANADA =================
  {
    id: "mcat_ca",
    name: "MCAT Canada",
    country: "Canada",
    level: "PG",
    eligibleCourses: ["Doctor of Medicine (M.D.)"],
    conductingBody: "AAMC",
    website: "https://students-residents.aamc.org",
    category: "Medical",
    examLevelScope: "National",
    score_type: "score",
    min_val: 472,
    max_val: 528,
    hint: "Range: 472 - 528"
  },
  {
    id: "lsat_ca",
    name: "LSAT Canada",
    country: "Canada",
    level: "PG",
    eligibleCourses: ["Juris Doctor (J.D.)", "LL.B."],
    conductingBody: "LSAC",
    website: "https://www.lsac.org",
    category: "Law",
    examLevelScope: "National",
    score_type: "score",
    min_val: 120,
    max_val: 180,
    hint: "Range: 120 - 180"
  },

  // ================= AUSTRALIA =================
  {
    id: "atar",
    name: "ATAR",
    country: "Australia",
    level: "UG",
    eligibleCourses: ["Bachelor Degrees (All streams)"],
    conductingBody: "Tertiary Admissions Centres (UAC, VTAC, QTAC, etc.)",
    website: "https://www.uac.edu.au",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 30,
    max_val: 99.95,
    hint: "Range: 30.00 - 99.95 ATAR score"
  },
  {
    id: "gamsat",
    name: "GAMSAT",
    country: "Australia",
    level: "PG",
    eligibleCourses: ["Doctor of Medicine (M.D.)", "Doctor of Dental Medicine"],
    conductingBody: "ACER (Australian Council for Educational Research)",
    website: "https://gamsat.acer.org",
    category: "Medical",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 100,
    hint: "Range: 0 - 100 overall score"
  },

  // ================= GERMANY =================
  {
    id: "abitur",
    name: "Abitur GPA",
    country: "Germany",
    level: "UG",
    eligibleCourses: ["Bachelor of Science", "Bachelor of Arts", "Staatsexamen Medicine"],
    conductingBody: "German State Ministries of Education",
    website: "https://www.kmk.org",
    category: "Science",
    examLevelScope: "National",
    score_type: "gpa",
    min_val: 1.0,
    max_val: 4.0,
    hint: "German GPA (1.0 is Best, 4.0 is passing)"
  },
  {
    id: "testas",
    name: "TestAS",
    country: "Germany",
    level: "UG",
    eligibleCourses: ["Bachelor Degrees for non-EU students"],
    conductingBody: "g.a.s.t. (Society for Academic Study Preparation)",
    website: "https://www.testas.de",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 70,
    max_val: 130,
    hint: "Standard Score Range: 70 - 130"
  },

  // ================= SINGAPORE =================
  {
    id: "singapore_a_levels",
    name: "Singapore-Cambridge GCE A-Level",
    country: "Singapore",
    level: "UG",
    eligibleCourses: ["Bachelor Degrees (NUS, NTU, SMU)"],
    conductingBody: "Singapore Examinations and Assessment Board (SEAB)",
    website: "https://www.seab.gov.sg",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 20,
    max_val: 90,
    hint: "Rank Points Range: 20 - 90"
  },

  // ================= UAE =================
  {
    id: "emsat_math",
    name: "EmSAT Achieve Mathematics",
    country: "United Arab Emirates",
    level: "UG",
    eligibleCourses: ["Bachelor Degrees (Engineering / Science)"],
    conductingBody: "UAE Ministry of Education",
    website: "https://emsat.moe.gov.ae",
    category: "Engineering",
    examLevelScope: "National",
    score_type: "score",
    min_val: 500,
    max_val: 2000,
    hint: "Range: 500 - 2000 score"
  },

  // ================= CHINA =================
  {
    id: "gaokao",
    name: "Gaokao",
    country: "China",
    level: "UG",
    eligibleCourses: ["Bachelor Degrees (All streams)"],
    conductingBody: "Ministry of Education of the People's Republic of China",
    website: "https://www.moe.gov.cn",
    category: "Science",
    examLevelScope: "National",
    score_type: "score",
    min_val: 100,
    max_val: 750,
    hint: "Total Score (Max is usually 750)"
  },

  // ================= INTERNATIONAL / GENERAL =================
  {
    id: "ielts",
    name: "IELTS Academic",
    country: "International",
    level: "UG",
    eligibleCourses: ["All Undergraduate & Postgraduate programs"],
    conductingBody: "IDP / British Council / Cambridge",
    website: "https://www.ielts.org",
    category: "Arts & Humanities",
    examLevelScope: "National",
    score_type: "gpa",
    min_val: 1.0,
    max_val: 9.0,
    hint: "Overall Band Score (Range: 1.0 - 9.0)"
  },
  {
    id: "toefl_ibt",
    name: "TOEFL iBT",
    country: "International",
    level: "UG",
    eligibleCourses: ["All Undergraduate & Postgraduate programs"],
    conductingBody: "Educational Testing Service (ETS)",
    website: "https://www.ets.org/toefl",
    category: "Arts & Humanities",
    examLevelScope: "National",
    score_type: "score",
    min_val: 0,
    max_val: 120,
    hint: "Total Score Range: 0 - 120"
  }
];

export const EXAM_DATABASE_METADATA = {
  last_verified: "2026-06-15T00:00:00Z"
};

const DATA_FRESHNESS_DAYS = 90;
const lastVerifiedTime = new Date(EXAM_DATABASE_METADATA.last_verified).getTime();
const daysElapsed = (Date.now() - lastVerifiedTime) / (1000 * 60 * 60 * 24);

if (daysElapsed > DATA_FRESHNESS_DAYS) {
  console.warn(`[examDatabase] WARNING: static dataset was last verified on ${EXAM_DATABASE_METADATA.last_verified} (exceeds freshness limit of ${DATA_FRESHNESS_DAYS} days). Consider reviewing and updating dynamic ranges and link parameters.`);
} else {
  console.log(`[examDatabase] Static dataset verification is current (last verified ${daysElapsed.toFixed(0)} days ago).`);
}
